export enum ClassesConstantsEnum {
  FETCH_CLASEES = 'FETCH_CLASEES',
  FETCH_CLASEES_BY_ID = 'FETCH_CLASEES_BY_ID',
  DELETE_CLASEES = 'DELETE_CLASEES',
  UPDATE_STATUS_CLASEES = 'UPDATE_STATUS_CLASEES',
  DELETE_CLASEES_SESSION = 'DELETE_CLASEES_SESSION',
  UPDATE_CLASEES_SESSION = 'UPDATE_CLASEES_SESSION'
}