export enum ClassesConstantsEnum {
  FETCH_CLASEES = 'FETCH_CLASEES',
  FETCH_CLASEES_BY_ID = 'FETCH_CLASEES_BY_ID',
  FETCH_SESSION_CLASEES_BY_ID = 'FETCH_SESSION_CLASEES_BY_ID',
  FETCH_GENERATED_CLASSES = 'FETCH_GENERATED_CLASSES',
  FETCH_PATCH_GENERATED_CLASSES = 'FETCH_PATCH_GENERATED_CLASSES',
  DELETE_CLASEES = 'DELETE_CLASEES',
  UPDATE_STATUS_CLASEES = 'UPDATE_STATUS_CLASEES',
  DELETE_CLASEES_SESSION = 'DELETE_CLASEES_SESSION',
  UPDATE_CLASEES_SESSION = 'UPDATE_CLASEES_SESSION',
  EDIT_CLASS_NAME = 'EDIT_CLASS_NAME',
}