export enum UserContactsEnum {
    FETCH_ALL_USERS = "FETCH_ALL_USERS",
    FETCH_USERS_BY_ID = "FETCH_USERS_BY_ID",
    CREATE_USER = "CREATE_USER",
    FETCH_CHECKINS_USER = "FETCH_CHECKINS_USER",
    CHECKIN_USERS = "CHECKIN_USERS",
    DELETE_USER = "DELETE_USER",
    UPDATE_USER = "UPDATE_USER",

    DELETE_STUDENTS = "DELETE_STUDENTS",
    FETCH_STUDENTS_BY_STATUS = "FETCH_STUDENTS_BY_STATUS",
    FETCH_STUDENTS_BY_ID = "FETCH_STUDENTS_BY_ID",
    UPDATE_STUDENTS = "UPDATE_STUDENTS",
    UPDATE_STUDENTS_STATUS = "UPDATE_STUDENTS_STATUS",

}