export enum UserContactsEnum {
    FETCH_ALL_USERS = "FETCH_ALL_USERS",
    CREATE_USER = "CREATE_USER",
    FETCH_CHECKINS_USER = "FETCH_CHECKINS_USER",
    CHECKIN_USERS = "CHECKIN_USERS",
    DELETE_USER = "DELETE_USER",
    UPDATE_USER = "UPDATE_USER",
}