export enum ScheduleConstantsEnum {
    FETCH_SCHEDULES_BY_PERIOD = "FETCH_SCHEDULES_BY_PERIOD",
    DELETE_SCHEDULE_BY_PERIOD = "DELETE_SCHEDULE_BY_PERIOD",
    GENERATE_SCHEDULE_ENTRY = "GENERATE_SCHEDULE_ENTRY",
    CREATE_CLASS = "CREATE_CLASS"
}
