
export enum NavigationEnum {
  LOGIN = 'LOGIN',
  REGISTRATION = 'REGISTRATION',
  REGISTRATION_FINAL = 'REGISTRATION_FINAL',
  FORGOT_PASSWORD_SEND_EMAIL = 'FORGOT_PASSWORD_SEND_EMAIL',
  FORGOT_PASSWORD_SEND_PASSWORD = 'FORGOT_PASSWORD_SEND_PASSWORD',
  PAYMENT_TRACKING_SET_UP = 'PAYMENT_TRACKING_SET_UP',
  //SHEDULE
  SHEDULE_DAY = 'SHEDULE_DAY',
  SHEDULE_WEEK = 'SHEDULE_WEEK',
  SHEDULE_MONTH = 'SHEDULE_MONTH',
  //CANCELLATION
  CANCELLATION_SCREEN = 'CancellationScreen',
  CONFIRM_CANCELLATION_SCREEN = 'ConfirmCancellationScreen',
  //ADD CLASS
  ADD_CLASS_SCREEN = 'AddClassScreen',
  ADD_NEW_TEACHER_SCREEN = 'AddNewTeacherScreen',
  ADD_BUSINESS_ACCOUNT_SCREEN = 'AddBusinessAccountScreen',
  SELECT_DATE_SCREEN = 'SelectDateScreen',
  DATE_RECURRENCE_SCREEN = 'DateRecurrenceScreen',
  DATE_PREVIEW_SCREEN = 'DatePreviewScreen',
  ADD_STUDENTS_SCREEN = 'AddStudentsScreen',
  NEW_STUDENT_SCREEN = 'NewStudentScreen',
  PREPAYMENT_CONFIGURATION_SCREEN = 'PrepaymentConfigurationScreen',
  //TABS
  HOME_SCREEN = 'HOME_SCREEN',
  STUDENTS_TAB = 'STUDENTS_TAB',
  SCHEDULE_TAB = 'SCHEDULE_TAB',
  TO_DO_TAB = 'TO_DO_TAB',
  CLASSES_TAB = 'CLASSES_TAB',
  MORE_TAB = 'MORE_TAB',
  //CLASSES
  CLASS_SCREEN = 'CLASS_SCREEN',
  EDIT_CLASS_SCREEN = 'EDIT_CLASS_SCREEN',
  CLASSES_PREVIEW_SCREEN = 'CLASSES_PREVIEW_SCREEN',
  CLASSES_EDIT_NAME_SCREEN = 'CLASSES_EDIT_NAME_SCREEN',
  CLASSES_EDIT_DATE_SCREEN = 'CLASSES_EDIT_DATE_SCREEN',
  CLASSES_EDIT_PREVIEW_SCREEN = 'CLASSES_EDIT_PREVIEW_SCREEN',
  CLASSES_STUDENT_SCREEN = 'CLASSES_STUDENT_SCREEN',
  CHANGE_STUDENT_SCREEN = 'CHANGE_STUDENT_SCREEN',
  //STUDENTS
  STUDENTS_SCREEN = 'STUDENTS_SCREEN',
  EDIT_STUDENTS_SCREEN = 'EDIT_STUDENTS_SCREEN',
  PREVIEW_STUDENTS_SCREEN = 'PREVIEW_STUDENTS_SCREEN',
  STUDENT_PAYMENTS_SCREEN = 'STUDENT_PAYMENTS_SCREEN',
  PAYMENTS_TABLE_SCREEN = 'PAYMENTS_TABLE_SCREEN',
  PAYMENT_STUDENT_TRACKING = 'PAYMENT_STUDENT_TRACKING',
  //MORE
  MORE_SCREEN = 'MORE_SCREEN',
  //MODALS
  RESULT_CLASS_MODAL = 'RESULT_CLASS_MODAL',
  SELECT_DURATION_CLASS_MODAL = 'SELECT_DURATION_CLASS_MODAL',
  EDIT_DURATION_CLASS_MODAL = 'EDIT_DURATION_CLASS_MODAL',
  EDIT_TIME_CLASS_MODAL = 'EDIT_TIME_CLASS_MODAL',
  PREVIEW_MODAL = 'PREVIEW_MODAL',
  CANCELLATION_MODAL = 'CANCELLATION_MODAL',
  LOCATION_CLASS_MODAL = 'LOCATION_CLASS_MODAL',
}
