export enum NavigationEnum {
  LOGIN = 'navigation/LOGIN',
  REGISTRATION = 'navigation/REGISTRATION',
  REGISTRATION_FINAL = 'navigation/REGISTRATION_FINAL',
  FORGOT_PASSWORD_SEND_EMAIL = 'navigation/FORGOT_PASSWORD_SEND_EMAIL',
  FORGOT_PASSWORD_SEND_PASSWORD = 'navigation/FORGOT_PASSWORD_SEND_PASSWORD',
  //TABS
  HOME_SCREEN = "navigation/HOME_SCREEN"
}
