export enum AuthContactsEnum {
    LOGIN = "IAuthContacts/LOGIN",
    REGISTRATION = "IAuthContacts/REGISTRATION",
    LOGOUT = "IAuthContacts/LOGOUT",
    RESET_PASSWORD_SEND_EMAIL = 'IAuthContacts/RESET_PASSWORD_SEND_EMAIL',
    RESET_PASSWORD_NEW_PASSWORD = 'IAuthContacts/RESET_PASSWORD_NEW_PASSWORD',
    RESET_PASSWORD_SEND_CODE = 'IAuthContacts/RESET_PASSWORD_SEND_CODE',
    CONFIRM_REGISTRATION_PASSWORD = 'IAuthContacts/CONFIRM_REGISTRATION_PASSWORD',
    GET_COUNTRIES = 'IAuthContacts/GET_COUNTRIES',
    GET_STATES = 'IAuthContacts/GET_STATES',
    GET_USER = 'IAuthContacts/GET_USER',
    USER_DEACTIVATE = 'IAuthContacts/USER_DEACTIVATE',
    USER_SEND_MAIN_DEACTIVATE = 'IAuthContacts/USER_SEND_MAIN_DEACTIVATE',
}